# Generated by Django 5.2.6 on 2025-09-12 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationjob',
            old_name='updated_at',
            new_name='translated_at',
        ),
        migrations.RenameField(
            model_name='translationjob',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='translationjob',
            name='error_message',
        ),
        migrations.AddField(
            model_name='translationjob',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translationjob',
            name='status',
            field=models.CharField(default='Hoàn thành', max_length=50),
        ),
    ]
